// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clwvbvabyqtqtywqimxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsd3ZidmFieXF0cXR5d3FpbXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTE2OTgsImV4cCI6MjA1ODkyNzY5OH0.hCZOR7zB-uHuVRIiIx4QJ_dAOnumwktb1i1_Tl_iJIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);