// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://docpyonaesnlwyeuvvik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY3B5b25hZXNubHd5ZXV2dmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODc4NDYsImV4cCI6MjA1NTU2Mzg0Nn0.utAoodol6vD_HeMm58BOkfP1wEjq__j5XoMtA06SGJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);